=== 3vivekb/matsim/matsim/dtd/households.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.matsim.org/files/dtd"
xmlns="http://www.matsim.org/files/dtd" elementFormDefault="qualified"
xml:lang="en">
<!-- Editor: Dominik Grether, VSP, Berlin Institute of Technology -->
<!-- This xml schema contains xml definitions for household information in the MATSim framework  -->

<xs:include schemaLocation="http://www.matsim.org/files/dtd/matsimCommon.xs"/>


<xs:element name="households">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="household" type="householdType"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:complexType name="householdType">
  <xs:annotation>
    <xs:documentation>This type contains all information to describe a MATSim household.</xs:documentation>
  </xs:annotation>
  <xs:complexContent>
    <xs:extension base="matsimObjectType">
    <xs:sequence>
      <xs:element name="members">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="person" type="idRefType" minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>    
      <xs:element name="location" type="locationType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="income" type="incomeType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="language" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
				  <xs:attribute name="name" type="xs:string" usage="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="type" type="xs:string" minOccurs="0" maxOccurs="1" />        
    </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>

<xs:complexType name="incomeType">
  <xs:complexContent>
    <xs:extension base="xs:decimal" />
  </xs:complexContent>
  <xs:attribute name="currency" type="xs:string" usage="required" />
  <xs:attribute name="period" type="incomePeriodType" usage="required" />
</xs:complexType>

<xs:simpleType name="incomePeriodType">
	<xs:restriction base="xs:string">
	  <xs:enumeration value="year" />
	  <xs:enumeration value="month" />
	  <xs:enumeration value="day" />
	  <xs:enumeration value="hour" />
	  <xs:enumeration value="second" />
	</xs:restriction>
</xs:simpleType>
</xs:schema>

=== 3vivekb/matsim/matsim/test/input/org/matsim/basic/testHouseholds.xml
<?xml version="1.0" encoding="UTF-8"?>
<households
  xmlns="http://www.matsim.org/files/dtd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/households.xsd">
  <household id="23">
    <members>
			<person refId="42" />
			<person refId="43" />
    </members>
    <location>
			<xCoord value="48.28"/>
			<yCoord value="7.56"/>
    </location>
    <income currency="eur">
			50000
    </income>
    <language name="SchwitzerdÃ¼tsch" /> 
    <type>
      StudentFlat
    </type>
  </household>

  <household id="24">
    <members>
			<person refId="44" />
			<person refId="45" />
    </members>

    <location>
      <facility refId="666" />
    </location>
  </household>
</households>
