=== 3vivekb/matsim/contribs/carsharing/src/main/resources/dtd/CarsharingStations.dtd
<?xml version="1.0" encoding="utf-8"?>

<!-- $Id$ -->

<!-- ============================================================ -->
<!ELEMENT stations          (twoway*,oneway*,freefloating*)>
<!ATTLIST stations
          name           CDATA   #IMPLIED
          reference_layer  CDATA #IMPLIED
          xml:lang       NMTOKEN "de-CH">

<!ELEMENT twoway          (vehicle*)>
<!ATTLIST twoway
          id           CDATA   #REQUIRED
          lat  	       CDATA #REQUIRED
          lon       CDATA #REQUIRED>

<!ELEMENT oneway          (vehicle*)>
<!ATTLIST oneway
          id           CDATA   #REQUIRED
          lat  	       CDATA #REQUIRED
          lon       CDATA #REQUIRED
	  freeparking	CDATA #REQUIRED>

<!ELEMENT freefloating          EMPTY>
<!ATTLIST freefloating
          id           CDATA   #REQUIRED
          lat  	       CDATA #REQUIRED
          lon       CDATA #REQUIRED
	  type	CDATA #REQUIRED>

<!ELEMENT vehicle         EMPTY>
<!ATTLIST vehicle
          type             CDATA                    #REQUIRED
          vehicleID            CDATA                    #REQUIRED>

=== 3vivekb/matsim/contribs/carsharing/test/input/org/matsim/contrib/carsharing/runExample/RunCarsharingTest/CarsharingStations.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE stations SYSTEM "CarsharingStations.dtd">
<stations>
	<twowaycarsharing id="1" lat="-375" lon="0" >
		<vehicle type="car" vehicleID="TW_1" />
		<vehicle type="car" vehicleID="TW_2" />
	</twowaycarsharing>
	<twowaycarsharing id="2" lat="0" lon="375" >
		<vehicle type="car" vehicleID="TW_3" />
		<vehicle type="car" vehicleID="TW_4" />
	</twowaycarsharing>
	<oneway id="1" lat="-375" lon="0" freeparking="2">
		<vehicle type="car" vehicleID="OW_1" />
		<vehicle type="car" vehicleID="OW_2" />
	</oneway>
	
	<freefloating id="FF_1" lat="-375" lon="0" type="car" />
			<freefloating id="FF_2" lat="0" lon="-375" type="car" />
			<freefloating id="FF_3" lat="-375" lon="0" type="car" />
			<freefloating id="FF_4" lat="0" lon=".75" type="car" />
		
</stations>
